apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
spec:
  selector:
    matchLabels:
      run: php-apache
  replicas: 1
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
        - name: php-apache
          image: k8s.gcr.io/hpa-example
          ports:
            - conatainerPort: 80
          resources:
            requests:
              cpu: 500m
            limits:
              cpu: 1000m

---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  labels:
    run: php-apache
spec:
  selector:
    run: php-apache
  ports:
    - port: 80

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  miniReplicas: 1 # min 1 replca of pod will be created
  maxReplicas: 10 # max 10 replca of pod will be created
  targetCPUUtilizationPercentage: 50 # This means that as soon as pods cpu reaches 50% of requested CPU(250m)
  # then replica of pod will be created
# In case of CPU utlilization > 50%, HPA will change the replicaset and will number of pods will be increased
# and as soon as load is reduced then it will be restored to default state(reflects in 5min by default)
